/* Synthetic append-only ledger tests. Node VM UI checks are not Safari or broker tests. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const C=require('../money/practice-core.js'),outcomes=[];
let seq=0;
const at='2026-10-22T12:00:00+08:00',day='2026-10-12';
function add(p,type,data,time=at){return C.dispatch(p,type,data,time,'ptest'+(++seq));}
function setup(support='supported'){return {platform:'虚构平台',support,capital:'仅使用1000元训练账本，不合并平台余额',evidence:'确认模拟标识，产品与五个入口',delay:'unknown',simulationConfirmed:true};}
function obs(date,price=4000,extra={}){return {date,price,previous:4000,quoteTime:date+'T15:00:00+08:00',source:'虚构测试行情',delay:'delayed',volume:'100',unit:'份',index:'未知',fact:'虚构价格事实',guess:'方向未知',counter:'尚未找到',next:'下个实际交易日核对',emotion:'平静',action:'空仓',...extra};}
function fixture(support='supported'){let p=C.initial();p=add(p,'setup',setup(support));p=add(p,'observation',obs('2026-10-08'));return add(p,'observation',obs('2026-10-09'));}
function plan(extra={}){return {date:day,price:4000,origin:'platform',fact:'虚构观察事实',guess:'方向不明确',reason:'流程演练，无获利优势',source:'虚构测试报价',quoteTime:day+'T10:00:00+08:00',delay:'unknown',checks:'北京10:00、14:40',...extra};}
function createPlan(p,extra={}){p=add(p,'plan',plan(extra));return {p,id:p.events[p.events.length-1].id};}
function order(planId,extra={}){return {planId,date:day,price:4000,qty:100,side:'buy',origin:'platform',source:'虚构委托',reference:'委托'+(++seq),...extra};}
function place(p,id,extra={}){p=add(p,'order',order(id,extra));return {p,oid:p.events[p.events.length-1].id};}
function fill(oid,extra={}){return {orderId:oid,time:day+'T10:01:00+08:00',price:4000,qty:100,fee:500,feeStatus:'confirmed',source:'虚构成交单',reference:'成交'+(++seq),confirmed:true,...extra};}
function bought(extra={}){let {p,id}=createPlan(fixture(),extra),r=place(p,id);p=add(r.p,'fill',fill(r.oid));return {p,id,oid:r.oid};}
function close(p,id,sellPrice=3900){const r=place(p,id,{side:'sell',date:'2026-10-13',price:sellPrice});return add(r.p,'fill',fill(r.oid,{time:'2026-10-13T10:01:00+08:00',price:sellPrice}));}
function review(planId){return {planId,known:'知道数量和费用，未知方向',execution:'先计划再登记，执行一致',attribution:'含费计算，市场结果未能归因',emotion:'平静',improvement:'下一次先算费用',quality:'按计划，盈利不代表能力'};}
function test(name,fn){try{fn();outcomes.push({name,pass:true});}catch(e){outcomes.push({name,pass:false,error:e.stack});}}
test('initial state has no trades, completed tasks, evidence or measured profit',()=>{const p=C.initial(),s=C.replay(p);assert.equal(s.mode,'simulation');assert.equal(s.plans.length,0);assert.equal(Object.keys(s.taskStates).length,0);assert.equal(C.account(s,'simulation').net,null);assert.equal(C.nextTask(s,day).id,'setup');assert.match(C.handover(p,day),/提醒：未启用/);});
test('fixed point preserves 0.001 price and 0.01 fee without rounding price first',()=>{assert.equal(C.fixed('4.001',1000),4001);assert.equal(C.fixed('0.29',100),29);assert.equal(C.amount(4001,100),40010);for(const x of ['-1','1e3','4.0001','','Infinity'])assert.equal(C.fixed(x,1000),null);});
test('verified calendar excludes weekends, adjustment workdays and holidays',()=>{assert.equal(C.tradingDay('2026-10-08'),true);for(const d of ['2026-10-07','2026-10-10','2026-10-11','2026-02-23'])assert.equal(C.tradingDay(d),false);assert.equal(C.nextTrading('2026-10-09'),'2026-10-12');assert.equal(C.nthTrading(day,5),'2026-10-16');assert.equal(C.tradingDays(day,'2026-10-16'),5);});
test('unknown future calendar does not pretend to know T+1 or observation days',()=>{assert.equal(C.tradingDay('2027-01-04'),null);assert.equal(C.nextTrading('2026-12-31'),null);assert.equal(C.nthTrading('2026-12-31',5),null);assert.throws(()=>add(fixture(),'observation',obs('2027-01-04')),/实际交易日/);});
test('ten day sequence is generated from calendar, not hardcoded weekend dates',()=>{const ds=['2026-10-08'];for(let i=1;i<10;i++)ds.push(C.nextTrading(ds[i-1]));assert.deepEqual(ds,['2026-10-08','2026-10-09','2026-10-12','2026-10-13','2026-10-14','2026-10-15','2026-10-16','2026-10-19','2026-10-20','2026-10-21']);});
test('observation needs actual day, source, time and fact/guess/check fields',()=>{for(const extra of [{date:'2026-10-10'},{date:'2026-02-30'},{source:''},{fact:''},{quoteTime:'2026-10-08T15:00:00+08:00'}])assert.throws(()=>add(fixture(),'observation',obs(day,4000,extra)));});
test('future observation/quote and future plans are rejected',()=>{assert.throws(()=>add(fixture(),'observation',obs('2026-10-23')),/未来/);assert.throws(()=>createPlan(fixture(),{date:'2026-10-23',quoteTime:'2026-10-23T10:00:00+08:00'}),/未来/);});
test('read explanations or mark task complete does not create preparation/observation/independence',()=>{const p=add(C.initial(),'task',{taskId:'setup',status:'completed',evidence:'读过解释'}),s=C.replay(p);assert.equal(s.setup,null);assert.equal(C.observationCount(s),0);assert.equal(C.ready(s),false);});
test('same observation date rejects duplicates but audit correction counts once',()=>{let p=fixture(),old=p.events[1].id;assert.throws(()=>add(p,'observation',obs('2026-10-08')),/已有记录/);p=add(p,'observation',obs('2026-10-08',3900,{supersedes:old,reason:'核对后更正报价'}));const s=C.replay(p);assert.equal(s.observations.length,3);assert.equal(C.observationCount(s),2);assert.equal(C.latestObservations(s)[0].price,3900);});
test('one observation is insufficient to register buy order',()=>{let p=add(C.initial(),'setup',setup());p=add(p,'observation',obs('2026-10-08'));const r=createPlan(p);assert.throws(()=>place(r.p,r.id),/两个实际交易日/);});
test('unsupported platform permits explicit manual simulation, not invented support',()=>{let r=createPlan(fixture('unsupported'));assert.throws(()=>place(r.p,r.id),/只能继续观察/);r=createPlan(fixture('unsupported'),{origin:'manual'});assert(place(r.p,r.id,{origin:'manual'}).p);});
test('10 CNY times 100 plus 5 fee cannot become executable under 1000 budget',()=>{const r=createPlan(fixture(),{price:10000}),s=C.replay(r.p);assert(C.blocks(s,s.plans[0],day).some(x=>x.includes('超出')));assert.throws(()=>place(r.p,r.id,{price:10000}),/超出可用现金/);});
test('submission freezes cash only, does not create position or measured profit',()=>{const r=createPlan(fixture()),q=place(r.p,r.id),s=C.replay(q.p),a=C.account(s,'simulation',day);assert.equal(a.cash,100000);assert.equal(a.frozen,40500);assert.equal(a.available,59500);assert.equal(a.qty,0);assert.equal(a.net,null);assert.equal(C.trade(s,s.plans[0]).first,null);});
test('partial fill and cancellation retain shares and release only unused reservation',()=>{const r=createPlan(fixture()),q=place(r.p,r.id);let p=add(q.p,'fill',fill(q.oid,{qty:40,fee:200})),s=C.replay(p),a=C.account(s,'simulation',day);assert.equal(a.qty,40);assert.equal(a.cash,83800);assert.equal(a.frozen,24300);p=add(p,'order_status',{orderId:q.oid,status:'cancelled',reason:'5分钟未全成交'});s=C.replay(p);a=C.account(s,'simulation',day);assert.equal(a.qty,40);assert.equal(a.frozen,0);assert.equal(a.available,83800);assert.equal(C.orderState(s,s.orders[0]).status,'cancelled');});
test('late backfill before cancellation is allowed and not treated as new order',()=>{const r=createPlan(fixture()),q=place(r.p,r.id);let p=add(q.p,'order_status',{orderId:q.oid,status:'cancelled',reason:'已撤剩余'});p=add(p,'fill',fill(q.oid,{qty:40,fee:200}));assert.equal(C.account(C.replay(p),'simulation',day).qty,40);assert.throws(()=>add(p,'fill',fill(q.oid,{qty:60,time:'2026-10-22T13:00:00+08:00'}),'2026-10-22T14:00:00+08:00'),/撤单之后/);});
test('T+1 has total 100 and sellable 0 on entry day, 100 next trading day',()=>{const {p,id}=bought(),s=C.replay(p);assert.equal(C.trade(s,s.plans[0],day).qty,100);assert.equal(C.trade(s,s.plans[0],day).sellable,0);assert.equal(C.trade(s,s.plans[0],'2026-10-13').sellable,100);assert.throws(()=>place(p,id,{side:'sell'}),/可卖数量/);});
test('Friday entry not sellable on weekend, sellable Monday',()=>{let r=createPlan(fixture(),{date:'2026-10-09',quoteTime:'2026-10-09T10:00:00+08:00'}),q=place(r.p,r.id,{date:'2026-10-09'});const p=add(q.p,'fill',fill(q.oid,{time:'2026-10-09T10:01:00+08:00'})),s=C.replay(p);assert.equal(C.trade(s,s.plans[0],'2026-10-10').sellable,0);assert.equal(C.trade(s,s.plans[0],day).sellable,100);});
for(const [sale,net]of [[3900,-2000],[4160,600],[3880,-2200]])test('1000 / 4x100 / fees5+5 / sell '+sale+' returns exact '+net+' cents',()=>{let {p,id}=bought();p=close(p,id,sale);const s=C.replay(p),t=C.trade(s,s.plans[0],'2026-10-13'),a=C.account(s,'simulation','2026-10-13');assert.equal(t.net,net);assert.equal(a.cash,100000+net);assert.equal(a.qty,0);assert.equal(a.equity,a.cash);});
test('buy fees not deducted twice in equity or liquidation estimate',()=>{let {p}=bought();p=add(p,'observation',obs(day));const a=C.account(C.replay(p),'simulation',day);assert.equal(a.equity,99500);assert.equal(a.liquidation,99000);assert.equal(a.net,-500);});
test('sell submission does not erase position; partial sale proportional cost and remaining shares',()=>{let {p,id}=bought(),q=place(p,id,{side:'sell',date:'2026-10-13',price:3900}),s=C.replay(q.p);assert.equal(C.trade(s,s.plans[0],'2026-10-13').qty,100);p=add(q.p,'fill',fill(q.oid,{time:'2026-10-13T10:01:00+08:00',qty:40,price:3900,fee:200}));s=C.replay(p);const t=C.trade(s,s.plans[0],'2026-10-13');assert.equal(t.qty,60);assert.equal(t.remainingCost,24300);assert.equal(t.closed,false);assert.throws(()=>add(p,'review',review(id)),/持仓未归零/);});
test('two pending sell orders cannot reserve same shares twice',()=>{const {p,id}=bought(),q=place(p,id,{side:'sell',date:'2026-10-13'});assert.throws(()=>place(q.p,id,{side:'sell',date:'2026-10-13'}),/已被卖出委托占用/);});
test('unknown fill fees are explicitly estimated from snapshot; unknown model has unknown profit',()=>{const r=createPlan(fixture()),q=place(r.p,r.id);const p=add(q.p,'fill',fill(q.oid,{fee:null,feeStatus:'unknown'})),s=C.replay(p);assert.equal(C.trade(s,s.plans[0]).estimated,true);assert.match(C.handover(p,day),/unknown/);let changed=JSON.parse(JSON.stringify(p));const set={timezone:'Asia/Ho_Chi_Minh',buyFee:null,sellFee:null,feeStatus:'unknown',feeSource:'未知',verifiedDate:null,reason:'未知占位测试'};changed.events.splice(3,0,{id:'punknownfee',at,type:'settings',data:set});assert.throws(()=>C.replay(changed),/费用未知/);});
test('confirmed zero fees are not replaced with 5 yuan',()=>{const r=createPlan(fixture()),q=place(r.p,r.id),p=add(q.p,'fill',fill(q.oid,{fee:0}));assert.equal(C.account(C.replay(p),'simulation',day).cash,60000);});
test('duplicate external fill references and overfills reject without mutating original',()=>{const {p,oid}=bought(),before=JSON.stringify(p),ref=p.events[p.events.length-1].data.reference;assert.throws(()=>add(p,'fill',fill(oid,{reference:ref})),/不能重复/);assert.throws(()=>add(p,'fill',fill(oid)),/不能超过/);assert.equal(JSON.stringify(p),before);});
test('plan revision keeps original and reason, active plans cannot be silently rewritten',()=>{let r=createPlan(fixture());r.p=add(r.p,'plan',plan({planId:r.id,price:3900,changeReason:'委托前更正'}));let s=C.replay(r.p);assert.equal(s.plans[0].versions.length,2);assert.equal(s.plans[0].versions[0].price,4000);const q=place(r.p,r.id,{price:3900});assert.throws(()=>add(q.p,'plan',plan({planId:r.id,changeReason:'持仓中改规则'})),/快照不能改/);});
test('settings new version affects new plans only, existing fee snapshot stays unchanged',()=>{const r=createPlan(fixture());const p=add(r.p,'settings',{timezone:'Asia/Shanghai',buyFee:100,sellFee:100,feeStatus:'verified',feeSource:'虚构已核实规则',verifiedDate:'2026-10-12',reason:'新计划适用'}),s=C.replay(p);assert.equal(s.settings.buyFee,100);assert.equal(s.plans[0].versions[0].buyFee,500);assert.equal(s.settingsHistory.length,1);});
test('position forbids second buy and averaging down',()=>{const {p}=bought(),r=createPlan(p);assert.throws(()=>place(r.p,r.id),/已有持仓/);});
test('closed trade prioritizes review, even if profitable; new buy waits',()=>{let {p,id}=bought();p=close(p,id,4160);const s=C.replay(p);assert.equal(C.nextTask(s,'2026-10-13').page,'review');const r=createPlan(p,{date:'2026-10-14',quoteTime:'2026-10-14T10:00:00+08:00'});assert.throws(()=>place(r.p,r.id,{date:'2026-10-14'}),/上一笔复盘/);});
test('two completed rounds cap is an upper limit, not a mandatory metric',()=>{let {p,id}=bought();p=add(close(p,id),'review',review(id));let r=createPlan(p,{date:'2026-10-14',quoteTime:'2026-10-14T10:00:00+08:00'}),q=place(r.p,r.id,{date:'2026-10-14'});p=add(q.p,'fill',fill(q.oid,{time:'2026-10-14T10:01:00+08:00'}));q=place(p,r.id,{side:'sell',date:'2026-10-15',price:4000});p=add(q.p,'fill',fill(q.oid,{time:'2026-10-15T10:01:00+08:00'}));p=add(p,'review',review(r.id));r=createPlan(p,{date:'2026-10-16',quoteTime:'2026-10-16T10:00:00+08:00'});assert.throws(()=>place(r.p,r.id,{date:'2026-10-16'}),/最多两个回合/);});
test('50 loss pause is sticky after recovery, permits exits and recording/review',()=>{let {p,id}=bought();p=add(p,'observation',obs('2026-10-13',3500));let s=C.replay(p);assert.equal(s.paused.simulation,true);p=add(p,'observation',obs('2026-10-14',4000));s=C.replay(p);assert.equal(s.paused.simulation,true);const q=place(p,id,{side:'sell',date:'2026-10-14'});p=add(q.p,'fill',fill(q.oid,{time:'2026-10-14T10:01:00+08:00'}));p=add(p,'review',review(id));assert.equal(C.account(C.replay(p),'simulation').qty,0);});
test('manual pause blocks new buying but does not block existing sell/cancel/fill/review',()=>{let {p,id}=bought();p=add(p,'pause',{mode:'simulation',reason:'没空检查，主动暂停'});const q=place(p,id,{side:'sell',date:'2026-10-13'});assert(q.p);const r=createPlan(p);assert.throws(()=>place(r.p,r.id),/已暂停/);});
test('holding day 5 is based on actual entry day, not route D7 or D10 deadline',()=>{const {p,id}=bought(),s=C.replay(p);assert.equal(C.trade(s,s.plans[0],'2026-10-16').exitDate,'2026-10-16');assert.match(C.exitCheck(s,C.planBy(s,id),'2026-10-16'),/第5个/);});
test('correction retains original fill and makes prior review require rechecking',()=>{let {p,id}=bought();p=add(close(p,id),'review',review(id));const s=C.replay(p),last=s.fills[s.fills.length-1];p=add(p,'fill_correction',{...last,fillId:last.id,price:3950,reason:'成交价核对更正'});const s2=C.replay(p);assert.equal(C.trade(s2,s2.plans[0]).net,-1500);assert.equal(s2.audit[s2.audit.length-1].original.price,3900);assert.equal(C.trade(s2,s2.plans[0]).reviewStale,true);assert.equal(C.nextTask(s2,'2026-10-22').page,'review');});
test('invalid correction cannot oversell or rewrite a buy date past a sell',()=>{let {p,id}=bought();p=close(p,id);const s=C.replay(p),f=s.fills[0];assert.throws(()=>add(p,'fill_correction',{...f,fillId:f.id,time:'2026-10-14T10:01:00+08:00',reason:'非法时间测试'}));});
test('full backup round trip and repeated restoration do not duplicate any fill or versions',()=>{let {p,id}=bought();p=add(close(p,id),'review',review(id));const backup=JSON.parse(JSON.stringify(p)),s=C.replay(backup);assert.equal(s.fills.length,2);assert.deepEqual(C.replay(JSON.parse(JSON.stringify(backup))),s);assert.equal(s.plans[0].versions.length,1);});
test('invalid schema, units, IDs, or relationships reject import instead of dropping data',()=>{for(const mutate of [p=>p.moneyUnit='yuan',p=>p.currency='USD',p=>p.format=2,p=>p.events.push({id:'bad',at,type:'question',data:{question:'x',answer:''}}),p=>p.events.push({...p.events[0]}),p=>p.events[0].type='unknown']){const p=fixture();mutate(p);assert.throws(()=>C.replay(p));}});
test('simulation profit or date passage cannot automatically switch to live',()=>{let {p,id}=bought();p=add(close(p,id,4160),'review',review(id));const s=C.replay(p);assert.equal(s.mode,'simulation');assert.equal(C.ready(s),false);assert.throws(()=>add(p,'live',{confirmed:true,reason:'赚钱就实盘'}),/不完整/);});
function readyFixture(){let {p,id}=bought();p=add(close(p,id),'review',review(id));let d=day;while(C.observationCount(C.replay(p))<10){p=add(p,'observation',obs(d));d=C.nextTrading(d);}for(const skill of Object.keys(C.SKILLS))p=add(p,'evidence',{skill,level:'independent',content:'虚构独立产出与检查依据',source:'合成测试'});p=add(p,'settings',{timezone:'Asia/Ho_Chi_Minh',buyFee:500,sellFee:500,feeStatus:'verified',feeSource:'虚构费用确认',verifiedDate:'2026-10-22',reason:'测试核实'});return p;}
test('live requires explicit user choice after complete evidence and fees; defaults stay simulation',()=>{const p=readyFixture(),s=C.replay(p);assert(C.ready(s));assert.equal(s.mode,'simulation');assert.throws(()=>add(p,'live',{confirmed:false,reason:'未选择'}));const next=add(p,'live',{confirmed:true,reason:'本人选择，理解不授权订单'});assert.equal(C.replay(next).mode,'live');assert.equal(C.account(C.replay(next),'live').initial,0);});
test('only one confirmed 1000 internal transfer, never add simulation platform account to real',()=>{let p=add(readyFixture(),'live',{confirmed:true,reason:'本人选择'});p=add(p,'funding',{amount:100000,source:'原现金归属名称',reference:'internal_test',confirmed:true});const s=C.replay(p);assert.equal(C.account(s,'live').initial,100000);assert.equal(C.account(s,'simulation').cash,98000);assert.throws(()=>add(p,'funding',{amount:100000,source:'追加',reference:'extra',confirmed:true}),/禁止追加/);});
test('hand manual simulation cannot be disguised as a live plan',()=>{const p=add(readyFixture(),'live',{confirmed:true,reason:'本人选择'});assert.throws(()=>createPlan(p,{origin:'manual'}),/只能用于模拟/);});
test('AI handoff has modes, quote provenance, unknown values, versions and no fake history',()=>{const text=C.handover(C.initial(),day);for(const x of ['模拟记录','待核实','下一步只做','不授权','费用']){if(x==='不授权')continue;assert(text.includes(x));}assert.match(text,/成交记录0/);assert.match(C.handover(fixture('unsupported'),day),/unsupported/);});
// UI integration with fake browser storage and DOM; no real browser state is changed.
function ui(seed={},broken=false){const map=new Map(Object.entries(seed)),nodes=new Map(),handlers=new Map();let quota=broken;const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',dataset:{},setAttribute(){},removeAttribute(){},focus(){},select(){},append(){},click(){},remove(){},addEventListener:(type,fn)=>handlers.set(id+':'+type,fn)});return nodes.get(id);};class D extends Date{constructor(...x){super(...(x.length?x:[new Date(at).getTime()]))}static now(){return new Date(at).getTime();}}
 const storage={getItem:k=>map.has(k)?map.get(k):null,setItem(k,v){if(quota)throw Error('quota');map.set(k,v)}};
 const ctx={TradingPractice:C,Intl,Date:D,localStorage:storage,console,FormData:class{constructor(f){this.values=f.values;}get(k){return this.values[k]??null;}has(k){return Object.hasOwn(this.values,k);}[Symbol.iterator](){return Object.entries(this.values)[Symbol.iterator]();}},navigator:{},setTimeout:()=>1,URL,Blob,File:class{},document:{querySelector:node,querySelectorAll:()=>[],createElement:node,body:node('body'),hidden:false,addEventListener:(type,fn)=>handlers.set('document:'+type,fn)}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../money/practice-ui.js'),'utf8'),ctx);
 return {map,node,handlers,quota:v=>quota=v,go(p){handlers.get('#nav:click')({target:{closest:()=>({dataset:{page:p}})}});},submit(type,values){const f={dataset:{form:type},values};handlers.get('#view:submit')({target:{closest:()=>f},preventDefault(){}});}};
}
test('UI initial page has one current setup action and correct no-result label',()=>{const a=ui();assert.match(a.node('#view').innerHTML,/准备中/);assert.match(a.node('#view').innerHTML,/开始今天任务/);assert.match(a.node('#view').innerHTML,/暂无可核实结果/);});
test('all five views and secondary settings render without browser/broker APIs',()=>{const a=ui({[C.KEY]:JSON.stringify(bought().p)});for(const page of ['today','observe','trades','review','route','settings']){a.go(page);assert(a.node('#view').innerHTML.length>100);}});
test('UI quota failure preserves old event state; retry stores one event only',()=>{const budget='{"plans":{"private":"keep"},"entries":[]}',a=ui({'money-route.v1':budget});a.go('settings');a.quota(true);a.submit('setup',{...setup(),simulationConfirmed:'on'});assert.equal(a.map.has(C.KEY),false);assert.match(a.node('#message').textContent,/未保存/);a.quota(false);a.submit('setup',{...setup(),simulationConfirmed:'on'});assert.equal(JSON.parse(a.map.get(C.KEY)).events.length,1);assert.equal(a.map.get('money-route.v1'),budget);});
test('cross-tab stale state cannot overwrite newer training records',()=>{const a=ui();a.map.set(C.KEY,JSON.stringify(fixture()));a.submit('question',{question:'待学',answer:''});assert.equal(JSON.parse(a.map.get(C.KEY)).events.length,3);assert.match(a.node('#message').textContent,/另一页面/);});
test('corrupt local practice data blocks writes without touching budgets',()=>{const a=ui({[C.KEY]:'{broken','money-route.v1':'keep'});assert.match(a.node('#view').innerHTML,/暂不可读/);a.submit('question',{question:'不能覆盖',answer:''});assert.equal(a.map.get(C.KEY),'{broken');assert.equal(a.map.get('money-route.v1'),'keep');});
test('rendered imported text is escaped instead of injected HTML',()=>{let p=add(fixture(),'question',{question:'<img src=x onerror=alert(1)>',answer:'<script>bad</script>'});const a=ui({[C.KEY]:JSON.stringify(p)});a.go('route');const html=a.node('#view').innerHTML;assert(html.includes('&lt;img'));assert(!html.includes('<img'));});
test('practice shell caches all new runtime files; existing root/index scope logic remains',()=>{const src=fs.readFileSync(path.join(__dirname,'../money/sw.js'),'utf8');for(const file of ['practice.html','practice.css','practice-core.js','practice-ui.js'])assert(src.includes("'./"+file+"'"));for(const file of ['practice-core.js','practice-ui.js'])new vm.Script(fs.readFileSync(path.join(__dirname,'../money/'+file),'utf8'));});
const report={date:'2026-10-05',suite:'money 1.1.0 trading practice',scope:'Synthetic core + Node VM DOM/storage. Not real browser, iPhone, broker or notifications.',total:outcomes.length,passed:outcomes.filter(x=>x.pass).length,failed:outcomes.filter(x=>!x.pass),checks:outcomes};
if(process.env.TEST_REPORT)fs.writeFileSync(path.resolve(__dirname,process.env.TEST_REPORT),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed},null,2));if(report.failed.length)process.exitCode=1;
