/* Run: node tests/regression.cjs. Synthetic data only; no dependencies.
   Real source functions run in a Node VM with DOM/storage/network substitutes.
   These checks are NOT real browser/iPhone end-to-end tests. */
const fs=require('fs'), vm=require('vm'), assert=require('assert'), path=require('path');
const root=path.join(__dirname,'..');
const outcomes=[];
const NativeDate=Date;
class FixedDate extends NativeDate { constructor(...a){super(...(a.length?a:['2026-10-04T03:00:00Z']))} static now(){return new NativeDate('2026-10-04T03:00:00Z').getTime()} }
function app(file,seed={},boot=false){
 const html=fs.readFileSync(path.join(root,file),'utf8'),src=html.match(/<script>([\s\S]*?)<\/script>/)[1];
 const nodes=new Map(), storage=new Map(Object.entries(seed)),handlers=new Map();
 const node=s=>{if(!nodes.has(s))nodes.set(s,{value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},getAttribute(){return ''},getBoundingClientRect(){return {width:390,height:170,left:0,top:0}},clientWidth:390,appendChild(){},remove(){},click(){},focus(){},select(){},scrollIntoView(){},contains(){return false},querySelector:x=>node(s+' '+x),querySelectorAll:()=>[],addEventListener:(k,f)=>handlers.set(s+':'+k,f)});return nodes.get(s)};
 const ctx={console,Date:FixedDate,Promise,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,document:{querySelector:node,querySelectorAll:()=>[],createElement:node,body:node('body'),addEventListener(){},hidden:false},window:{scrollTo(){},addEventListener(){},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}},navigator:{},URL,Blob,File:class{constructor(parts,name){this.text=parts.join('');this.name=name}},FileReader:class{readAsText(file){this.result=file.text;this.onload()}},location:{protocol:'http:'}};
 vm.createContext(ctx); new vm.Script(src);
 if(boot) vm.runInContext(src,ctx);
 else {vm.runInContext(src.split('/* ---------- events ---------- */')[0].replace('(function(){',''),ctx);vm.runInContext('render=function(){};',ctx)}
 return {ctx,node,storage,handlers,run:s=>vm.runInContext(s,ctx),json:s=>JSON.parse(vm.runInContext('JSON.stringify('+s+')',ctx)),seedState:value=>{ctx.value=value;vm.runInContext('state=cleanState(value);committed=JSON.stringify(state);',ctx)},failWrites(){ctx.window.localStorage.setItem=()=>{throw Error('quota')}},restoreWrites(){ctx.window.localStorage.setItem=(k,v)=>storage.set(k,v)}};
}
function moneyState(){return {plans:{'2026-10':{income:800000,save:200000,copied:false,cats:[{id:'food',name:'吃饭',cap:100000,fixed:false},{id:'rent',name:'房租',cap:200000,fixed:true}]}},entries:[]}}
function moneyBackup(st=moneyState()){return {app:'money-route',format:1,currency:'CNY',unit:'cents',...st}}
function studyState(){return {units:[{id:'u1',start:'2026-10-04',closed:false,concept:{name:'机会成本'},skill:{name:'说明问题',reps:[]}}],log:[],books:[],goals:[]}}
function draft(overrides={}){return {unitId:'u1',kind:'skill',step:3,elapsed:60000,stepMs:1000,first:false,revealed:false,grade:null,f:{goal:'说清楚',did:'完成一次',next:'放慢'},...overrides}}
function setMoneyForm(a,{date='2026-10-04',cat='food',amount='10'}={}){a.node('#e-amt').value=amount;a.node('#e-date').value=date;a.node('#e-cats input:checked').value=cat}
function submit(a,fn='submitEntry'){a.run(fn+'({preventDefault:function(){}})')}
function importObject(a,obj){a.ctx.file={text:JSON.stringify(obj),size:JSON.stringify(obj).length};a.run('readBackup(file)')}
async function test(name,fn){try{await fn();outcomes.push({name,pass:true})}catch(e){outcomes.push({name,pass:false,error:e.stack});}}
(async()=>{
 await test('all six JavaScript sources parse',()=>{for(const f of ['index.html','study/index.html','money/index.html','sw.js','study/sw.js','money/sw.js']){let s=fs.readFileSync(path.join(root,f),'utf8');if(f.endsWith('.html'))s=s.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(s)}});
 for(const file of ['index.html','study/index.html','money/index.html'])await test(file+' boot with simulated DOM',()=>app(file,{},true));
 await test('health explicit zero survives cleaning and goal comparison',()=>{let a=app('index.html');assert.equal(a.run('cleanRec({date:"2026-10-04",exMin:0}).exMin'),0);assert.equal(a.run('met({type:"move",exMin:20},cleanRec({date:"2026-10-04",exMin:0}))'),false);assert.equal(a.run('met({type:"move",exMin:20},{date:"2026-10-04"})'),null)});
 await test('health accepts and saves zero-only entry',async()=>{let a=app('index.html');a.run('state.ready=true');a.node('#f-date').value='2026-10-04';a.node('#f-exmin').value='0';submit(a);await Promise.resolve();assert.equal(JSON.parse(a.storage.get('health-route.v1')).days['2026-10-04'].exMin,0)});
 await test('health zero chart is recorded, without counting exercise',()=>{let a=app('index.html');a.run('state.ready=true;drawMove(["2026-10-04"],{"2026-10-04":{exMin:0}},null)');assert.match(a.node('#s-move').textContent,/记录 1 天 · 运动 0 次/)});
 await test('health failed save/delete rolls back',async()=>{let a=app('index.html');await a.run('saveDay({date:"2026-10-04",weight:70})');a.failWrites();await assert.rejects(a.run('saveDay({date:"2026-10-04",weight:71})'));assert.equal(a.run('state.days["2026-10-04"].weight'),70);await assert.rejects(a.run('removeDay("2026-10-04")'));assert.equal(a.run('state.days["2026-10-04"].weight'),70)});
 await test('health old format 1 backup imports and exports zero',()=>{let a=app('index.html');let data={app:'health-route',format:1,goal:{type:'move',exTimes:3,exMin:20},days:{'2026-10-03':{date:'2026-10-03',exMin:0}}};importObject(a,data);assert(a.run('!!pendingImport'));a.run('applyImport()');assert.equal(a.run('state.days["2026-10-03"].exMin'),0);assert(a.run('validBackup(backupData())'))});
 await test('money failed save retry creates only one entry',()=>{let a=app('money/index.html');a.seedState(moneyState());setMoneyForm(a);a.failWrites();submit(a);assert.equal(a.run('state.entries.length'),0);assert.equal(a.node('#e-amt').value,'10');a.restoreWrites();submit(a);assert.equal(a.run('state.entries.length'),1);assert.equal(a.run('stats("2026-10").total'),1000)});
 await test('money exact cents and fixed reserve remain correct',()=>{let a=app('money/index.html');let st=moneyState();st.entries=[{id:'x1',date:'2026-10-04',cat:'rent',amt:150000,adj:false},{id:'x2',date:'2026-10-04',cat:'food',amt:1234,adj:false}];a.seedState(st);assert.equal(a.run('toCents("0.29")'),29);assert.equal(a.run('stats("2026-10").flexLeft'),398766);assert.equal(a.run('stats("2026-10").flexSpent'),1234)});
 await test('money cross-month form shows historical categories',()=>{let a=app('money/index.html');let st=moneyState();st.plans['2026-09']={income:800000,save:200000,cats:[{id:'oldfood',name:'旧分类',cap:100000,fixed:false}]};a.seedState(st);a.node('#e-date').value='2026-09-20';a.run('renderEntry()');assert.match(a.node('#e-cats').innerHTML,/旧分类/);assert(!a.node('#e-cats').innerHTML.includes('房租'));setMoneyForm(a,{date:'2026-09-20',cat:'rent'});submit(a);assert.equal(a.run('state.entries.length'),0);setMoneyForm(a,{date:'2026-09-20',cat:'oldfood'});submit(a);assert.equal(a.run('state.entries.length'),1)});
 await test('money month rollover copies plan without sharing category objects',()=>{let a=app('money/index.html');let st=moneyState();st.plans['2026-09']=st.plans['2026-10'];delete st.plans['2026-10'];a.seedState(st);a.run('ensurePlan();state.plans["2026-10"].cats[0].name="新分类"');assert.equal(a.run('state.plans["2026-09"].cats[0].name'),'吃饭');assert.equal(a.run('state.plans["2026-10"].copied'),true)});
 await test('money old plan import preserves categories referenced by current entries',()=>{let a=app('money/index.html'),st=moneyState();st.entries=[{id:'e1',date:'2026-10-04',cat:'rent',amt:100000,adj:false}];a.seedState(st);const older=moneyState();older.plans['2026-10'].cats=[];importObject(a,moneyBackup(older));a.run('applyImport()');assert.equal(a.run('stats("2026-10").flexSpent'),0);assert.equal(a.run('catName(planOf("2026-10"),"rent")'),'房租');assert.equal(JSON.parse(a.storage.get('money-route.v1.beforeImport')).entries.length,1)});
 await test('money import failed main write leaves pending data retryable',()=>{let a=app('money/index.html');a.seedState(moneyState());const next=moneyState();next.entries=[{id:'e1',date:'2026-10-04',cat:'food',amt:1234,adj:false}];importObject(a,moneyBackup(next));a.ctx.window.localStorage.setItem=(k,v)=>{if(k==='money-route.v1')throw Error('quota');a.storage.set(k,v)};a.run('applyImport()');assert.equal(a.run('state.entries.length'),0);assert(a.run('!!pendingImport'));a.restoreWrites();a.run('applyImport()');assert.equal(a.run('state.entries.length'),1)});
 await test('money invalid schema, currency and amount units rejected without mutation',()=>{let a=app('money/index.html');a.seedState(moneyState());for(const change of [{format:99},{unit:'yuan'},{currency:'USD'},{app:'study-route'}]){importObject(a,{...moneyBackup(),...change});assert.equal(a.run('pendingImport'),null)}});
 await test('money rejects duplicate IDs and missing category links',()=>{let a=app('money/index.html');const data=moneyBackup();data.entries=[{id:'e1',date:'2026-10-04',cat:'missing',amt:1000,adj:false}];importObject(a,data);assert.equal(a.run('pendingImport'),null);data.entries=[];data.plans['2026-10'].cats.push(data.plans['2026-10'].cats[0]);importObject(a,data);assert.equal(a.run('pendingImport'),null)});
 await test('money same-ID conflicting entries rejected rather than silently lost',()=>{let a=app('money/index.html'),st=moneyState();st.entries=[{id:'e1',date:'2026-10-04',cat:'food',amt:1000,adj:false}];a.seedState(st);const b=moneyBackup(JSON.parse(JSON.stringify(st)));b.entries[0].amt=2000;importObject(a,b);assert.equal(a.run('pendingImport'),null);assert.equal(a.run('state.entries[0].amt'),1000)});
 await test('study failed finish retry creates only one practice and log',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d');a.failWrites();a.run('finishSession()');assert.equal(a.run('state.units[0].skill.reps.length'),0);assert(a.run('!!draft'));a.restoreWrites();a.run('finishSession()');assert.equal(a.run('state.units[0].skill.reps.length'),1);assert.equal(a.run('state.log.length'),1);assert.equal(JSON.parse(a.storage.get('study-route.v1')).draft,null)});
 await test('study completion and clearing draft are one main write, even legacy removal fails',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d');a.storage.set('study-route.draft',JSON.stringify(draft()));a.ctx.window.localStorage.removeItem=()=>{throw Error('denied')};a.run('finishSession()');let b=app('study/index.html',Object.fromEntries(a.storage));b.run('load()');assert.equal(b.run('draft'),null);assert.equal(b.run('state.units[0].skill.reps.length'),1)});
 await test('study migrates legacy draft and retains fuzzy rating and typed text',()=>{let d=draft({kind:'concept',step:0,grade:'fuzzy'});d.f.recall='隔天回想';let a=app('study/index.html',{'study-route.v1':JSON.stringify(studyState()),'study-route.draft':JSON.stringify(d)});a.run('load();saveDraft()');assert.equal(a.run('draft.grade'),'fuzzy');assert.equal(JSON.parse(a.storage.get('study-route.v1')).draft.f.recall,'隔天回想')});
 await test('study draft migration keeps uncompleted text longer than final note limit',()=>{let d=draft();d.f.did='草稿'.repeat(500);let a=app('study/index.html',{'study-route.v1':JSON.stringify(studyState()),'study-route.draft':JSON.stringify(d)});a.run('load();saveDraft()');assert.equal(a.run('draft.f.did.length'),1000)});
 await test('study draft backup restores into empty app',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d');let b=app('study/index.html');importObject(b,a.json('backupData()'));assert(b.run('!!pendingImport'));b.run('applyImport()');assert.equal(b.run('draft.f.goal'),'说清楚');assert.equal(b.run('currentUnit().id'),'u1')});
 await test('study old no-draft backup remains importable',()=>{let a=app('study/index.html');importObject(a,{app:'study-route',format:1,...studyState()});assert(a.run('!!pendingImport'));a.run('applyImport()');assert.equal(a.run('state.units.length'),1);assert.equal(a.run('draft'),null)});
 await test('study two draft conflict is explicit and preserves current draft',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d');importObject(a,{app:'study-route',format:1,...studyState(),draft:draft({f:{goal:'另一份'}})});assert.equal(a.run('pendingImport'),null);assert.equal(a.run('draft.f.goal'),'说清楚')});
 await test('study current draft unit survives old notes import',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d;state.units[0].concept.what="新解释";saveDraft()');const old=studyState();old.units[0].concept.what='旧解释';importObject(a,{app:'study-route',format:1,...old});a.run('applyImport()');assert.equal(a.run('state.units[0].concept.what'),'新解释');assert.equal(a.run('draft.f.goal'),'说清楚')});
 await test('study failed new unit creation keeps current draft and active unit',()=>{let a=app('study/index.html');a.seedState(studyState());a.ctx.d=draft();a.run('draft=d;saveDraft();ui.form="new"');a.node('#u-concept').value='新概念';a.node('#u-skill').value='新技能';a.failWrites();submit(a,'submitUnit');assert.equal(a.run('state.units.length'),1);assert.equal(a.run('currentUnit().id'),'u1');assert.equal(a.run('draft.unitId'),'u1')});
 await test('study same-day recall does not pass next-day criterion',()=>{let a=app('study/index.html');a.run('var c=cleanConcept({firstSaid:"2026-10-04",box:0,due:"2026-10-05"});applyGrade(c,"ok")');assert.equal(a.run('c.recalledOn'),null);assert.equal(a.run('c.box'),0)});
 await test('imported unsafe/reserved identifiers are rejected',()=>{for(const payload of ['\"><img src=x onerror="window.X=1">','__proto__','constructor','prototype']){let a=app('study/index.html');importObject(a,{app:'study-route',format:1,...studyState(),books:[{id:payload,title:'书'}]});assert.equal(a.run('pendingImport'),null);let b=app('money/index.html'),data=moneyBackup();data.plans['2026-10'].cats[0].id=payload;importObject(b,data);assert.equal(b.run('pendingImport'),null)}});
 await test('HTML identifiers escaped even for previously stored unsafe values',()=>{const payload='\"><img src=x onerror="window.X=1">';let a=app('study/index.html');a.ctx.payload=payload;a.run('state.books=[cleanBook({id:payload,title:"书"})];renderShelf()');assert(!a.node('#bookList').innerHTML.includes('<img'));assert(a.node('#bookList').innerHTML.includes('&lt;img'));let b=app('money/index.html');b.ctx.payload=payload;b.run('state.plans[thisYm()]=cleanPlan({income:800000,save:200000,cats:[{id:payload,name:"分类"}]});renderEntry()');assert(!b.node('#e-cats').innerHTML.includes('<img'))});
 for(const [file,key] of [['index.html','health-route.v1'],['study/index.html','study-route.v1'],['money/index.html','money-route.v1']])await test(file+' unreadable original is preserved and writes blocked',()=>{let a=app(file,{[key]:'{broken'});a.run(file==='index.html'?'readLocal()':'load()');assert(a.run('readFailure'));a.run(file==='index.html'?'writeLocal()':'save()');assert.equal(a.storage.get(key),'{broken');let captured;a.ctx.navigator.canShare=()=>true;a.ctx.navigator.share=({files})=>{captured=files[0];return Promise.resolve()};a.run('exportBackup()');assert.equal(captured.text,'{broken');assert.match(captured.name,/raw-recovery/)});
 for(const file of ['index.html','study/index.html','money/index.html'])await test(file+' previous snapshot failure prevents import mutation',()=>{let a=app(file);const data=file==='index.html'?{app:'health-route',format:1,goal:null,days:{'2026-10-04':{date:'2026-10-04',weight:70}}}:file.startsWith('study')?{app:'study-route',format:1,...studyState()}:moneyBackup();importObject(a,data);assert(a.run('!!pendingImport'));let before=a.json('backupData()');a.failWrites();a.run('applyImport()');assert.deepEqual(a.json('backupData()'),before);assert(a.run('!!pendingImport'))});
 // Service worker behavior including event lifetime and cache isolation.
 function sw(file,{status=503,offline=false,cacheFail=false,cached=true,slow=false}={}){
  const handlers={},writes=[],waits=[],timers=[];let response,release;
  const home='https://example.test/health-route/'+(file.includes('/')?file.split('/')[0]+'/':'');
  const store={match:async()=>cached?new Response('cached-app'):undefined,put:async(k,v)=>{if(cacheFail)throw Error('quota');writes.push([typeof k==='string'?k:k.url,await v.text()])}};
  const fetched=()=>offline?Promise.reject(Error('offline')):Promise.resolve(new Response(status===200?'new-app':'server-error',{status}));
  const ctx={self:{location:{href:home+'sw.js',origin:'https://example.test'},addEventListener:(k,f)=>handlers[k]=f},URL,Promise,TypeError,setTimeout:f=>{timers.push(f);return 1},clearTimeout(){},fetch:()=>slow?new Promise(r=>release=()=>fetched().then(r)):fetched(),caches:{open:async()=>store}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
  const call=(url=home,mode='navigate')=>{handlers.fetch({request:{method:'GET',url,mode},respondWith:p=>response=p,waitUntil:p=>waits.push(p)});return response};
  return {call,waits,writes,timers,release:()=>release(),home};
 }
 for(const file of ['sw.js','study/sw.js','money/sw.js']){
  await test(file+' 503 navigation serves cache',async()=>{let s=sw(file);let r=await s.call();assert.equal(r.status,200);assert.equal(await r.text(),'cached-app');await Promise.all(s.waits)});
  await test(file+' offline navigation serves cache',async()=>{let s=sw(file,{offline:true});assert.equal(await (await s.call()).text(),'cached-app')});
  await test(file+' successful response caches both document entry URLs',async()=>{let s=sw(file,{status:200});assert.equal(await (await s.call()).text(),'new-app');await Promise.all(s.waits);assert(s.writes.some(([k])=>k===s.home+'index.html'));assert(s.writes.every(([,v])=>v==='new-app'))});
  await test(file+' cache write failure does not hide network response',async()=>{let s=sw(file,{status:200,cacheFail:true});assert.equal((await s.call()).status,200);await Promise.all(s.waits)});
  await test(file+' slow network serves cache and later updates it',async()=>{let s=sw(file,{status:200,slow:true});let promise=s.call();s.timers[0]();assert.equal(await (await promise).text(),'cached-app');s.release();await Promise.all(s.waits);assert.equal(s.writes.length,3)});
  await test(file+' ignores other app subfolders',()=>{let s=sw(file);assert.equal(s.call(s.home+'other/index.html'),undefined)});
  await test(file+' missing assets are not replaced with app HTML',async()=>{let s=sw(file,{status:404});assert.equal((await s.call(s.home+'missing.png','cors')).status,404)});
 }
 await test('offline and no cache rejects navigation',async()=>{let s=sw('sw.js',{offline:true,cached:false});await assert.rejects(s.call())});
 const failed=outcomes.filter(x=>!x.pass);
 console.log(JSON.stringify({total:outcomes.length,passed:outcomes.length-failed.length,failed},null,2));
 if(process.env.TEST_REPORT)fs.writeFileSync(process.env.TEST_REPORT,JSON.stringify({method:'Node VM with simulated DOM/storage/network; no real-browser/iPhone validation',total:outcomes.length,passed:outcomes.length-failed.length,outcomes},null,2));
 if(failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
