(function(){
'use strict';
const C=TradingPractice,$=s=>document.querySelector(s),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={simulation:'模拟记录',live:'实盘记录',platform:'平台模拟',manual:'手工模拟（成交未经撮合验证）',unverified:'待核实',supported:'已核实支持',unsupported:'平台不支持',unknown:'待核实',hypothetical:'演练假设',verified:'已核实',estimated:'估算',confirmed:'已核实',realtime:'即时（本人核实）',delayed:'已知延迟',submitted:'已委托，尚未成交',partial:'部分成交',filled:'全部成交',cancelled:'已撤（已成交保留）',failed:'拒单/失败',not_started:'未开始',in_progress:'进行中',completed:'完成（仅任务，不代表独立掌握）',skipped:'跳过',paused:'暂停',explained:'已讲',tried:'已尝试',independent:'可独立完成'};
const label=v=>labels[v]||v,money=v=>v===null?'待核实':'¥'+(v/100).toFixed(2),price=v=>v===null?'未知':(v/1000).toFixed(3),now=()=>new Date().toISOString(),today=()=>C.marketDate(now());
const G=TradingGuide;
const startPage=location.hash.slice(1);
let data=C.initial(),raw=null,failed=false,page=['today','observe','trades','review','route','settings','setup'].includes(startPage)?startPage:'today',pending=null;
function message(s){$('#message').textContent=s;}
function load(){try{raw=localStorage.getItem(C.KEY);data=raw?JSON.parse(raw):C.initial();C.replay(data);failed=false;}catch(e){failed=true;message('本机练习数据读取失败：'+e.message+'。写入已暂停，请导出原始数据后联系维护。');}}
function commit(next){if(failed)throw Error('读取失败，不能覆盖本机记录');if(localStorage.getItem(C.KEY)!==raw)throw Error('另一页面已修改练习记录，请刷新后重试，当前输入尚未清除');C.replay(next);const out=JSON.stringify(next);localStorage.setItem(C.KEY,out);raw=out;data=next;}
function save(type,body){commit(C.dispatch(data,type,body));render();message('已保存到本机。');}
const options=(items,value)=>items.map(([v,t])=>`<option value="${esc(v)}"${v===value?' selected':''}>${esc(t)}</option>`).join('');
function field(name,title,value='',type='text'){return `<label>${esc(title)}<input name="${esc(name)}" type="${type}" value="${esc(value)}"${type==='text'?' autocomplete="off"':''}></label>`;}
function area(name,title,value=''){return `<label>${esc(title)}<textarea name="${esc(name)}">${esc(value)}</textarea></label>`;}
function select(name,title,items,value=''){return `<label>${esc(title)}<select name="${esc(name)}">${options(items,value)}</select></label>`;}
function check(name,title){return `<label class="check"><input type="checkbox" name="${esc(name)}">${esc(title)}</label>`;}
function form(type,content,button){return `<form data-form="${type}">${content}<button class="primary" type="submit">${esc(button)}</button></form>`;}
function panel(title,body){return `<section class="panel"><h2>${title}</h2>${body}</section>`;}
function record(title,body,tail=''){return `<article class="record"><h3>${title}</h3>${body}${tail}</article>`;}
function fmtTime(value,zone){return new Intl.DateTimeFormat('zh-CN',{timeZone:zone,dateStyle:'short',timeStyle:'short',hour12:false}).format(new Date(value));}
function localStamp(){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ','T');return parts+'+08:00';}
function marketStatus(){const day=today(),t=C.tradingDay(day);if(t===null)return '交易日历待核实（目前仅核实2026年；不按工作日猜开市）';if(!t)return '休市日 · 可学习，不计观察交易日';const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());return (p>='09:30'&&p<'11:30'||p>='13:00'&&p<'15:00')?'计划交易时段 · 停牌/临时休市仍需核实':'交易日 · 当前非连续交易时段（以平台为准）';}
function taskPanel(s){const g=G.get(C,s,today());return `<section class="hero"><div class="row"><span class="badge">${label(s.mode)}</span><span class="eyebrow">${esc(C.stage(s))}</span></div><h2 class="task">${esc(g.title)}</h2><p>${esc(g.why)}</p>${g.wait?`<p class="hint">${esc(g.wait)}</p>`:''}<ol class="steps">${g.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><button class="primary" data-go="${g.page}">${esc(g.button)}</button><p class="hint">约 ${g.task.minutes} 分钟 · ${esc(marketStatus())}</p></section>`;}
function todayView(s){const task=C.nextTask(s,today()),a=C.account(s,s.mode,today()),status=s.taskStates[task.id];return taskPanel(s)+`<details class="panel"><summary>训练账本 · 观察 ${C.observationCount(s,today())}/10</summary><div class="metrics"><div class="metric"><span>初始预算（与平台大账户分开）</span><b>${s.mode==='live'?money(a.initial):'¥1,000'}</b></div><div class="metric"><span>${label(s.mode)}净损益${a.estimate?' · 估算':''}</span><b>${a.net===null?'暂无可核实结果':money(a.net)}</b></div><div class="metric"><span>持仓份额</span><b>${a.qty}</b></div></div><p class="hint">现金（含委托冻结）${money(a.cash)}；冻结 ${money(a.frozen)}；可用 ${money(a.available)}。</p><p class="hint">${a.quote?'估值来源 '+esc(a.quote.source)+' · '+esc(a.quote.quoteTime)+' · '+label(a.quote.delay):'没有报价记录。无成交时不显示“0元盈利”。'} ${a.manual?'手工成交未经撮合，不证明真实下单能力。':''}</p><p class="warning">3% / 4% / 5天、50元只是流程参数，不保证收益或损失上限。</p></details><details class="panel"><summary>补充任务状态或卡住的原因</summary><p class="hint">读过解释不会自动完成观察或升级掌握。真实准备、观察和成交仍需分别保存。</p>`+form('task',`<input type="hidden" name="taskId" value="${esc(task.id)}">${select('status','当前任务状态',Object.keys(labels).filter(k=>['not_started','in_progress','completed','skipped','paused'].includes(k)).map(k=>[k,label(k)]),status?status.status:'not_started')}${area('evidence','这次做了什么／为什么跳过或暂停',status?status.evidence:'')}`,'保存任务状态')+'</details>';}
function lessonView(s){const g=G.learning(C,s,today()),previous=s.questions.filter(q=>q.question===g.question).slice(-1)[0];return panel('先看懂一个小概念',`<p class="eyebrow">${esc(g.title)}</p><p>${esc(g.explain)}</p><div class="example"><p>${esc(g.example)}</p></div><p class="hint">${g.wait?esc(g.wait):'先自己解释，再核对参考。虚构例子不会变成成交或观察记录。'}</p>`+form('question',`<input type="hidden" name="question" value="${esc(g.question)}"><p><b>试着回答：</b>${esc(g.question)}</p>${area('answer','用自己的话说（不懂就写卡在哪里）',previous?previous.answer:'')}`,'保存这次解释')+`<details><summary>展开参考解释</summary><p>${esc(g.answer)}</p><p class="hint">用了参考就按“有提示”记录；保存解释不自动升级独立掌握。</p></details><details><summary>没看懂，交给 GPT 继续教</summary><p class="hint">复制时会带上当前解释和实际进度。App 不自动调用 GPT。</p><button type="button" id="copy-lesson">复制当前问题与进度</button><textarea id="lesson-prompt" readonly hidden></textarea></details>`);}
function observeView(s){const rows=C.latestObservations(s),todayRecord=rows.find(o=>o.date===today()),open=C.tradingDay(today())===true&&!todayRecord;return lessonView(s)+`<details class="panel" id="observation-entry"${open?' open':''}><summary>${todayRecord?'今天已保存 · 需要时更正':'记录一个实际交易日'}</summary><p class="hint">行情来自你的外部工具。按北京时间填写；数值缺失可空，文字未知要如实注明。休市日可补记历史交易日，不填未来日期。</p>`+form('observation',`${select('supersedes','新记录或纠错（原记录保留）',[['','新记录'],...rows.map(o=>[o.id,'纠错 '+o.date])],todayRecord?todayRecord.id:'')}<div class="pair">${field('date','数据对应的交易日',C.tradingDay(today())===true?today():'','date')}${field('quoteTime','该日行情时间，带 +08:00 或 +07:00',C.tradingDay(today())===true?localStamp():'')}</div><div class="pair">${field('price','510300 收盘价格（元，可空）')}${field('previous','前收盘价格（元，可空）')}</div>${field('source','行情来源（不填账户信息）')}${area('fact','事实：今天观察到了什么')}${area('guess','推测：我怎么解释／还有什么可能')}${area('next','下次只检查什么') }<details><summary>其他观察项 · 未核实可写未知</summary><div class="pair">${field('volume','成交量／额','未知')}${field('unit','量的单位（份／手／元）','未知')}</div>${field('index','沪深300表现／点数','未知')}${select('delay','行情延迟',[['unknown','待核实'],['delayed','已知延迟'],['realtime','本人核实即时']])}${area('counter','反对证据','尚未核实')}${field('action','实际持仓动作',C.account(s,s.mode,today()).qty?'持仓动作待核实':'空仓，继续观察')}${field('emotion','情绪','未记录')}${field('reason','仅纠错时：修改原因')}</details>`,'保存今天的观察')+`</details><details class="panel"><summary>历史观察 · ${rows.length} 条</summary>`+(rows.length?rows.slice().reverse().map(o=>record(esc(o.date)+' · 510300',`<p>收盘 ${price(o.price)}${o.previous===null||o.price===null?' · 涨跌幅未知':' · 自算涨跌幅 '+((o.price-o.previous)/o.previous*100).toFixed(2)+'%'}</p><p>事实：${esc(o.fact)}</p><p>推测：${esc(o.guess)}</p><p>反证：${esc(o.counter)}</p><p>下一步：${esc(o.next)}</p><small>${esc(o.source)} · ${esc(o.quoteTime)} · ${label(o.delay)}；量 ${esc(o.volume)} ${esc(o.unit)}；指数 ${esc(o.index)}</small>`)).join(''):'<p class="hint">尚未保存观察，不补成已完成。</p>')+'</details>';}
function tradeView(s){const plans=s.plans.filter(p=>p.mode===s.mode),orders=s.orders.filter(o=>C.planBy(s,o.planId).mode===s.mode),fills=s.fills.filter(f=>C.planBy(s,C.orderBy(s,f.orderId).planId).mode===s.mode);
 const planOptions=plans.map(p=>[p.id,p.id+' · v'+p.versions.length]),orderOptions=orders.map(o=>[o.id,(o.side==='buy'?'买':'卖')+' '+o.qty+'份 · '+label(C.orderState(s,o).status)+' · '+o.id]);
 let out=panel(label(s.mode)+' · 先建计划',`<p class="warning">以下按钮只保存记录，不发送证券订单。手工模拟必须保留当时真实报价，不事后挑最低/最高价；日线路径未知时不能登记成确定成交。</p><details><summary>保存新计划／未委托计划的新版本</summary>`+form('plan',`${select('planId','计划范围',[['','新的流程演练计划'],...plans.filter(p=>!orders.some(o=>o.planId===p.id)).map(p=>[p.id,'新版本 '+p.id])])}${field('changeReason','改版本时必填原因（委托后不能改快照）')}${field('date','计划/行情日期',today(),'date')}${select('origin','演练来源',[['platform','平台模拟'],['manual','手工模拟，成交未经撮合验证']])}${field('price','最高可接受买价，100份（元）')}${area('fact','买前观察事实')}${area('guess','预测／未知（允许方向不明确）')}${area('reason','买入理由','流程演练：学习委托与费用，尚无经过验证的价格预测优势。')}${field('source','当时行情来源')}${field('quoteTime','行情时间，带 +08:00 或 +07:00',localStamp())}${select('delay','行情延迟',[['unknown','待核实'],['delayed','已知延迟'],['realtime','本人核实即时']])}${field('checks','可实际执行的检查时间','北京10:00、14:40（越南09:00、13:40）')}`,'保存计划（是否可执行另行检查）')+`</details><p class="hint">新计划快照：预算1000元；买费 ${money(s.settings.buyFee)}、卖费 ${money(s.settings.sellFee)}（${label(s.settings.feeStatus)}）；成交均价下方3%/上方4%；成交日算第1天，最迟第5交易日14:40安排退出。未成交顺延处理，不伪造退出。</p>`);
 out+=panel('计划与持仓',plans.length?plans.slice().reverse().map(p=>{const t=C.trade(s,p,today()),v=C.snapshot(p),rs=C.blocks(s,p,v.date);return record(esc(p.id)+' · v'+p.versions.length+ ' · '+label(p.mode),`<p>最高买价 ${price(v.price)} × 100；买费 ${money(v.buyFee)}（${label(v.feeStatus)}）</p><p>${t.bought?'总持仓 '+t.qty+'；当前可卖 '+(t.sellable===null?'待核实':t.sellable)+'；成交均价 '+price(t.avg):'尚无成交，不开始持有计时'}</p>${t.first?`<p>首笔成交 ${esc(t.first)}；持有交易日 ${t.holdingDays===null?'待核实':t.holdingDays}；第5日 ${t.exitDate||'日历待核实'}。退出参考 ${price(t.down)} / ${price(t.up)}（原值 ${esc(t.downRaw)} / ${esc(t.upRaw)} milliCNY，向下/上取整到0.001元）。</p>`:''}<p>${t.closed?'已退出；净损益 '+money(t.net)+(t.estimated?'（估算）':''):'买入可执行检查：'+(rs.length?esc(rs.join('；')):'记录条件齐备，不代表建议买入')}</p><details><summary>原计划与版本原因</summary><pre class="mono">${esc(JSON.stringify(p.versions,null,2))}</pre></details>`);}).join(''):'<p class="hint">0笔计划。先完成准备和两天观察，再考虑练习。</p>');
 if(plans.length)out+=panel('登记外部委托（不是下单）',form('order',`${select('planId','关联计划',planOptions)}<div class="pair">${select('side','买卖方向',[['buy','买入记录'],['sell','卖出记录']])}${field('date','实际委托日期',today(),'date')}</div><div class="pair">${field('price','限价（元）')}${field('qty','委托数量（买100份，卖按实际可卖）','100')}</div>${select('origin','成交来源',[['platform',s.mode==='live'?'本人真实平台记录':'平台模拟'],['manual','手工模拟，未经撮合验证']])}${field('reference','委托编号或自定义标识（不填账号）')}${area('source','实际委托依据／平台与时间')}`,'登记委托'));
 if(orders.length)out+=panel('委托不等于成交',orders.slice().reverse().map(o=>{const z=C.orderState(s,o);return record(esc(o.id),`<p>${o.side==='buy'?'买入':'卖出'} ${o.qty}份 @ ${price(o.price)}；已成交 ${z.filled}；${label(z.status)}</p><small>${label(o.origin)} · ${esc(o.date)} · ${esc(o.reference)}</small>`);}).join('')+`<details><summary>登记撤单／拒单</summary>`+form('order_status',`${select('orderId','关联委托',orderOptions)}${select('status','状态',[['cancelled','已撤（保留已成交部分）'],['failed','拒单／失败']])}${area('reason','原因与核对依据')}`,'登记状态')+`</details>`);
 if(orders.length)out+=panel('登记实际成交／纠错',`<p class="hint">部分成交逐条记。费用是本条分摊费用，不是每次都重复填整笔5元；待核实费用留空，报表使用计划占位时标“估算”。“0”只用于确认实际为0。晚补已撤单前成交，填写真实成交时间。</p>`+form('fill',`${select('fillId','新成交或纠错（原事件不删除）',[['','新的成交记录'],...fills.map(f=>[f.id,'纠错 '+f.reference+' · '+f.id])])}${select('orderId','关联委托',orderOptions)}${field('reference','成交编号（重复标识不重复计数）')}${field('time','真实成交时间，带时区',localStamp())}<div class="pair">${field('price','成交价（元，最多3位小数）')}${field('qty','本条成交数量（可部分成交）')}</div><div class="pair">${field('fee','本条分摊费用（元，待核实可空）')}${select('feeStatus','费用状态',[['unknown','待核实'],['estimated','已填写估算'],['confirmed','已核实实际费用']])}</div>${area('source','成交依据；手工需写当时可见报价来源、路径与时间')}${field('reason','纠错时：修改原因')}${check('confirmed','我核对了代码510300、模式、价格、数量、真实时间与费用；手工成交只是明确假设，不把日线碰价当确定成交。')}`,'登记成交（不发送订单）'));
 if(fills.length)out+=panel('已登记成交与审计',fills.map(f=>record(esc(f.reference),`<p>${esc(f.qty)}份 @ ${price(f.price)}；费用 ${money(f.fee)}（${label(f.feeStatus)}）</p><small>${esc(f.time)} · ${esc(f.source)}</small>`)).join('')+`<details><summary>保留的成交纠错历史</summary><pre class="mono">${esc(JSON.stringify(s.audit.filter(a=>a.type==='fill_correction'),null,2))}</pre></details>`);return out;}
function reviewView(s){const ps=s.plans.filter(p=>p.mode===s.mode&&C.trade(s,p).closed),a=C.account(s,s.mode,today());let out=panel('先复盘，再考虑下一笔',`<p>${s.paused[s.mode]?'已暂停新买入：'+esc(s.pauseReasons[s.mode]):'没有持仓也可以回顾；不为凑次数交易。'}</p><p class="hint">首阶段最多2个完整回合，不是必须完成的指标。盈利与执行质量分别记录；不年化，不排名。</p>`);
 if(ps.length)out+=panel('单笔五问',form('review',`${select('planId','已退出的计划',ps.map(p=>[p.id,p.id]))}${area('known','1. 买前真正知道什么，哪些只是推测')}${area('execution','2. 原计划是什么，实际做了什么／偏差原因')}${area('attribution','3—4. 核对含费损益；市场／假设／执行／费用，无法判断写未知')}${field('quality','执行质量（和盈利分开）')}${field('emotion','当时情绪')}${area('improvement','5. 下次只改善哪一个动作')}`,'完成本笔复盘'));
 out+=panel('复盘记录',s.reviews.length?s.reviews.slice().reverse().map(r=>{const p=C.planBy(s,r.planId),t=C.trade(s,p);return record(esc(r.planId)+' · '+label(p.mode),`<p>净损益 ${money(t.net)}${t.estimated?' · 估算':''}；执行质量 ${esc(r.quality)}${t.reviewStale?' · 成交纠错后需重新核对复盘':''}</p><p>实际与偏差：${esc(r.execution)}</p><p>归因：${esc(r.attribution)}</p><p>一个改进：${esc(r.improvement)}</p>`);}).join(''):'<p class="hint">尚无复盘，不冒充已经做过交易。</p>');
 return out+panel('阶段选择与主动暂停',form('decision',`${select('choice','我现在的选择',[['continue_simulation','继续模拟（不重置亏损）'],['pause','暂停新交易'],['long_term_only','只保留长期投资，结束短线练习'],['maintain_live','保持原小额（不加本金）']])}${area('reason','为什么这样选／每周20分钟回顾的结论')}`,'保存本人选择')+`<p class="hint">保守清算估计 ${money(a.liquidation)}；触及50元暂停参考后不会自动恢复。暂停不锁住卖出、撤单、补记录和复盘。</p>`);}
function routeView(s){
 const stages=[['S0','准备','确认模拟标识、产品支持、虚拟本金、费用和入口'],['S1','两天观察','两个真实交易日的观察记录'],['S2','流程演练','买前计划、委托、实际成交、退出与复盘可对应；允许空仓'],['S3','能力检查','10个实际观察日；至少一笔完整复盘；各项能力有独立证据'],['S4','小额实盘（可选）','所有证据和费用核实齐备，本人主动选择；不授权证券订单'],['S5','阶段总结','选择继续模拟、保持小额、暂停或只做长期投资，不加本金']];
 const skills=Object.entries(C.SKILLS),independent=skills.filter(([key])=>{const e=s.evidence.filter(e=>e.skill===key).slice(-1)[0];return e&&e.level==='independent';}).length,task=C.nextTask(s,today());
 let out=panel('当前进度',`<p>${esc(C.stage(s))} · 实际观察 ${C.observationCount(s,today())} / 10 个交易日</p><p>本人登记的独立证据 ${independent} / ${skills.length} 项</p><p class="hint">独立证据来自本人记录，App 没有自动核实；读过解释或保存答案不会增加它。</p><p><b>下一步：</b>${esc(task.text)}</p><details><summary>展开完整路线和每日重点</summary>${stages.map(([id,t,desc])=>`<div class="route-row"><b>${id}</b><div><h3>${t}</h3><p class="hint">${desc}</p></div></div>`).join('')}<h3>D1—D10每天一个重点</h3>${C.TOPICS.map((t,i)=>`<p class="hint">D${i+1} · ${esc(t)}</p>`).join('')}<p class="hint">日历核实范围2026年；<a href="${C.CALENDAR_SOURCE}" target="_blank" rel="noopener noreferrer">上交所休市公告</a>。其他年份待核实。</p></details>`);
 out+=panel('交给 GPT 继续',`<p class="hint">带上实际进度、未理解的问题和下一步。不会自动发送；复制前可展开核对自己的文字。</p><div class="actions"><button class="primary" id="copy">复制接手摘要</button><button id="md">导出 Markdown</button></div><details id="handoff-preview"><summary>预览完整接手文档</summary><label>接手摘要<textarea id="handoff" readonly>${esc(C.handover(data,today()))}</textarea></label></details>`);
 out+=`<details class="panel"><summary>查看或补充能力证据 · ${s.evidence.length} 条记录</summary><p class="hint">一次只补一项，保留实际产出和完成方式。</p>`+skills.map(([key,t])=>{const e=s.evidence.filter(e=>e.skill===key).slice(-1)[0];return record(esc(t),`<p>${e?label(e.level)+'：'+esc(e.content):'未开始 / 没有证据'}</p>`);}).join('')+form('evidence',`${select('skill','这次记录哪一项',skills)}${select('level','实际完成方式',[['explained','已讲：只听过解释'],['tried','已尝试：有提示或示范'],['independent','可独立完成：有真实独立产出']])}${area('content','实际解释／练习结果与检查依据（不是一句“懂了”）')}${field('source','依据来源／日期；不要账户或密码')}`,'保存能力证据')+'</details>';
 return out+`<details class="panel"><summary>问题停车场与已保存解释 · ${s.questions.length} 条</summary>`+form('question',`${area('question','只记一个未理解的问题')}${area('answer','已理解的解释（可留空）')}`,'保存问题')+s.questions.slice().reverse().map(q=>record(esc(q.question),`<p>${esc(q.answer||'待学习')}</p>`)).join('')+'</details>';
}
function setupView(s){const setup=s.setup||{};return panel('S0 · 准备证据',`<p class="hint">在iPhone查找官方同花顺模拟工具；只用普通应用账号，不转真钱。核对买、卖、委托/撤单、成交、持仓入口。若510300不支持，保留观察与明确手工模拟，不改成杠杆或个股。</p>`+form('setup',`${field('platform','实际使用的模拟工具',setup.platform||'同花顺模拟炒股')}${select('support','510300是否支持模拟交易',[['unverified','尚未核实'],['supported','本人核实支持'],['unsupported','平台不支持']],setup.support||'unverified')}${field('capital','是否能设1000元／实际平台虚拟本金是多少',setup.capital||'')}${select('delay','行情延迟',[['unknown','未核实'],['delayed','已知延迟'],['realtime','本人核实即时']],setup.delay||'unknown')}${area('evidence','实际找到的产品、五个入口与尚未核实项',setup.evidence||'')}${check('simulationConfirmed','我已经确认该外部账户明确标注“模拟”；不是实盘账户。')}`,'保存准备证据'));
}
function settingsView(s){let out=`<details class="panel"><summary>查看或修改准备证据</summary>${setupView(s)}</details>`;
 out+=panel('费用与时区（仅作用于新计划）',form('settings',`${select('timezone','用户时区',[['Asia/Ho_Chi_Minh','越南 UTC+7'],['Asia/Shanghai','北京 UTC+8']],s.settings.timezone)}<div class="pair">${field('buyFee','买入费用占位／核实额（元，可空）',s.settings.buyFee===null?'':(s.settings.buyFee/100).toFixed(2))}${field('sellFee','卖出费用占位／核实额（元，可空）',s.settings.sellFee===null?'':(s.settings.sellFee/100).toFixed(2))}</div>${select('feeStatus','费用依据状态',[['hypothetical','演练假设（初始买/卖各5元）'],['unknown','完全未知'],['verified','核实后的预算估计（逐笔实际费仍另登记）']],s.settings.feeStatus)}${field('feeSource','收费规则来源（不存账号）',s.settings.feeSource)}${field('verifiedDate','核实日期（核实后必填）',s.settings.verifiedDate||'','date')}${area('reason','这次设置或规则变更原因（旧计划快照不改）')}`,'保存新设置版本')+`<p class="hint">本金1000元、不加仓、不加杠杆、100份、最多一笔持仓、首阶段最多两回合。第一版不提供持仓中扩大亏损容忍线的设置。</p><p class="hint">建议复盘时间20:30（用户时区）；持仓检查北京10:00 / 14:40，越南09:00 / 13:40。提醒未启用，不支持可靠后台推送或实时价格监控，请在外部工具自行核实设置。</p>`);
 out+=panel('实盘记录：必须本人主动选择',`<p class="warning">${C.ready(s)?'准备证据齐备，仍不代表有盈利能力。':'当前不满足实盘准备：需10个真实观察日、完整复盘、全部独立证据和费用核实。'}此按钮只切换记录模式，不开户、不转账、不授权AI或App发出证券订单。</p>`+form('live',`${area('reason','本人选择的理由与能接受损失的说明')}${check('confirmed','我主动选择开始小额实盘记录，理解1000元预算和50元非保证损失上限，并已核实账户资格、ETF权限、费用和可执行检查时间。')}`,'主动选择实盘记录'));
 if(s.mode==='live'&&!s.funding)out+=panel('登记已发生的真实内部划转',`<p class="warning">原App没有持仓/现金总账。这里只登记归属，不自动增加家庭资产或扣原预算。请在实际资产账本按“原现金−1000、练习子账户+1000”记一次，不重复计入总资产。没有实际划转就不要确认。</p>`+form('funding',`${field('source','原现金账户归属名称（不要账号）')}${field('reference','内部划转关联标识')}${check('confirmed','本人确认已划转1000元，并在原资产账本去重；不追加或重置亏损。')}`,'登记1000元内部划转'));
 out+=panel('交易练习备份（与预算备份分开）',`<p class="hint">只保存在本设备。原理财首页的备份只含记账和预算；这里的JSON完整保存计划版本、委托、成交、复盘、证据和纠错。换设备前两处分别导出。备份含本人文字，不公开分享。</p><div class="actions"><button id="export">${failed?'导出原始练习数据':'导出练习 JSON'}</button><button id="import"${failed?' disabled':''}>选择练习备份</button><button id="previous">导出导入前副本</button></div><input id="file" type="file" accept="application/json,.json" hidden>${pending?`<p class="warning">确认后只整体替换交易练习，不改记账预算。将恢复 ${pending.events.length} 个历史事件；相同备份再次恢复不会重复成交。导入前自动保存本机副本。</p><div class="actions"><button class="primary" id="import-confirm">确认恢复练习备份</button><button id="import-cancel">取消</button></div>`:''}`);return out;}
function render(){if(failed){page='settings';$('#view').innerHTML=panel('练习记录暂不可读','<p>写入与导入已暂停，原记账预算未改。先导出原始练习数据，再刷新或联系维护。</p><button id="export">导出原始练习数据</button>');$('#storage-status').textContent='读取失败 · 尚未改动原数据';return;}const s=C.replay(data);$('#storage-status').textContent=`仅保存在本机 · ${label(s.mode)} · ${fmtTime(now(),s.settings.timezone)}（${s.settings.timezone}） / 北京 ${fmtTime(now(),'Asia/Shanghai')}`;document.querySelectorAll('[data-page]').forEach(b=>{if(b.dataset.page===page||page==='setup'&&b.dataset.page==='today')b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const views={today:todayView,observe:observeView,trades:tradeView,review:reviewView,route:routeView,settings:settingsView,setup:setupView};$('#view').innerHTML=views[page](s);}
function decimal(value,scale,title,optional=false){if(!value.trim()&&optional)return null;const n=C.fixed(value,scale);if(n===null||scale===1000&&n===0)throw Error(title+'请输入有效非负金额，价格最多3位／费用最多2位小数');return n;}
$('#view').addEventListener('submit',ev=>{const f=ev.target.closest('form[data-form]');if(!f)return;ev.preventDefault();message('');try{const values=new FormData(f),get=k=>String(values.get(k)||'').trim(),kind=f.dataset.form,b={};for(const [k,v]of values)b[k]=String(v).trim();if(kind==='setup')b.simulationConfirmed=values.has('simulationConfirmed');if(kind==='settings'){b.buyFee=decimal(get('buyFee'),100,'买费',true);b.sellFee=decimal(get('sellFee'),100,'卖费',true);b.verifiedDate=get('verifiedDate')||null;}
 if(kind==='observation'){b.price=decimal(get('price'),1000,'收盘价',true);b.previous=decimal(get('previous'),1000,'前收盘价',true);}
 if(kind==='plan'||kind==='order'||kind==='fill')b.price=decimal(get('price'),1000,'价格');if(kind==='order'||kind==='fill')b.qty=Number(get('qty'));
 if(kind==='fill'){b.fee=decimal(get('fee'),100,'费用',true);b.confirmed=values.has('confirmed');}if(kind==='live'||kind==='funding')b.confirmed=values.has('confirmed');if(kind==='funding')b.amount=100000;
 save(kind==='fill'&&get('fillId')?'fill_correction':kind,b);if(kind==='question')message('解释已保存，可继续核对参考或交给GPT；观察天数和掌握状态未自动改变。');if(kind==='setup'){go('today');message('准备证据已保存。接下来只做首页这一小步。');}if(kind==='observation'){go('today');message('观察已保存。首页已按真实记录更新下一步。');}
 }catch(e){message('未保存：'+e.message+'。输入仍保留。');}});
function go(next){if(!['today','observe','trades','review','route','settings','setup'].includes(next))return;page=next;message('');render();$('#view').focus();}
$('#nav').addEventListener('click',ev=>{const b=ev.target.closest('[data-page]');if(b)go(b.dataset.page);});$('#settings').addEventListener('click',()=>go('settings'));
async function download(text,name,type){try{const f=new File([text],name,{type});if(navigator.canShare&&navigator.canShare({files:[f]})){await navigator.share({files:[f],title:'理财航线交易练习'});message('已交给系统分享，请确认保存到“文件”。');return;}}catch(e){if(e.name==='AbortError')return;}const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);message('已生成 '+name+'，请确认保存文件。');}
$('#view').addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.go){go(b.dataset.go);return;}try{if(b.id==='export'){await download(failed?(raw||''):JSON.stringify(data,null,2),'money-practice-'+(failed?'raw-':'backup-')+today()+'.json','application/json');}
 if(b.id==='previous'){const old=localStorage.getItem(C.KEY+'.beforeImport');if(!old)throw Error('还没有导入前副本');await download(old,'money-practice-before-import-'+today()+'.json','application/json');}
 if(b.id==='copy'){try{await navigator.clipboard.writeText($('#handoff').value);message('已复制，可粘贴给GPT；先核对个人信息。');}catch(e){$('#handoff-preview').open=true;$('#handoff').focus();$('#handoff').select();message('自动复制不可用，摘要已展开并选中，请手动复制。');}}
 if(b.id==='copy-lesson'){const f=$('form[data-form=question]'),answer=f?String(new FormData(f).get('answer')||''):'';const text=G.prompt(C,C.replay(data),today(),answer)+'\n\n'+C.handover(data,today());$('#lesson-prompt').value=text;try{await navigator.clipboard.writeText(text);message('已复制当前问题和进度，可粘贴给GPT继续这一小步。');}catch(e){$('#lesson-prompt').hidden=false;$('#lesson-prompt').focus();$('#lesson-prompt').select();message('已显示并选中摘要，请手动复制。');}}
 if(b.id==='md')await download(C.handover(data,today()),'money-practice-handover-'+today()+'.md','text/markdown');
 if(b.id==='import')$('#file').click();if(b.id==='import-cancel'){pending=null;render();}
 if(b.id==='import-confirm'){if(!pending)return;if(localStorage.getItem(C.KEY)!==raw)throw Error('本机已变化，请刷新后重新选择备份');localStorage.setItem(C.KEY+'.beforeImport',raw||JSON.stringify(data));commit(pending);pending=null;render();message('练习备份已恢复；原预算未改，导入前副本可导出。');}
 }catch(e){message('未完成：'+e.message);}});
$('#view').addEventListener('change',async ev=>{if(ev.target.id!=='file')return;const file=ev.target.files&&ev.target.files[0];ev.target.value='';pending=null;if(!file)return;try{if(file.size>6*1024*1024)throw Error('备份超过6MB');const candidate=JSON.parse(await file.text());C.replay(candidate);pending=candidate;render();message('格式已核对，尚未覆盖本机记录。');}catch(e){message('未导入：'+e.message);}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(localStorage.getItem(C.KEY)!==raw){message('其他页面的记录有变化，请刷新；当前输入不会自动清除。');}else if(page==='today')render();}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
load();render();
})();
